### ISSUE TITLE
How to get the first residual during inference?

### ISSUE THREAD

**Issue by earthpimp** [DeminYu98/DiffCast#5]
Sorry to bother you. I am a bit confused about the inference part of Diffcast.

If I understand correctly, during network training, UNet model receives the followings as inputs,
1.) residual of last chunk (fragment)
2.) guiding information from context_net
3.) and also the fragment id
and learns to predict the noise/velocity_field.

However, during inference (real-time), how could we get the very-first-chunk / very-first-step residual (I am refering to the s_hat_{j-1} when j=1 in Fig. 2b inference box of your paper)?

Thank you for help in advance.

Edited:
I just looked at the sample method in diffcast.py. Seems like a zero tensor is used as the condition (since the input is actually the ground truth) to predict the residual for [5:10] at first, and then this predicted residual will be used to predict the next fragment residual. Am I understanding it correctly?

**Comment by DeminYu98** [comment]
Yep, that is correct.
Since the input seq can be considered as the ground truth, we take the first residual as zeros.
